name: Validate, Build, and Test

on:
  push:
    branches:
      - '**' # This will trigger the workflow on a push to any branch
  pull_request:
    branches:
      - main # This triggers the workflow on PRs targeting the main branch
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # New job to build the project and create the dist artifact
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Build TypeScript
        run: npm run build
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: dist/

  test:
    runs-on: ubuntu-latest
    # This job doesn't need the build artifact as it builds inside Docker
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t dropdown-list-badge-test .

      - name: Verify dist folder in image
        run: docker run --rm dropdown-list-badge-test ls -l dist

      - name: Start server
        run: |
          docker run --name dropdown-list-badge-server -d -p 5000:5000 dropdown-list-badge-test npx serve -l 5000 .
          sleep 5

      - name: Run Playwright tests
        run: |
          docker run --rm --network host \
            -v ${{ github.workspace }}/tests:/app/tests \
            -v ${{ github.workspace }}/tests/__snapshots__:/app/tests/__snapshots__ \
            -v ${{ github.workspace }}/tests/test-results:/app/tests/test-results \
            -v ${{ github.workspace }}/tests/html-report:/app/tests/html-report \
            dropdown-list-badge-test npx playwright test --config=tests/playwright.config.ts

      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: tests/html-report

      - name: Stop server
        run: docker rm -f dropdown-list-badge-server || true

  # This job now only commits the dist artifact, and only on pushes to main
  commit_dist:
    runs-on: ubuntu-latest
    needs: [build, test] # Run after build and test succeed
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-artifact
          path: dist
      - name: Commit and push `dist` directory
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Build and commit dist folder for HACS"
          file_pattern: dist/
          commit_options: '--no-verify'
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com

  validate-hacs:
    runs-on: ubuntu-latest
    needs: [build, test] # Run after build and test succeed
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-artifact
          path: dist
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: "plugin"
